// SPDX-License-Identifier: Apache-2.0
//! `Command` → `&'static str` tag mapper.
//!
//! One match against the closed `Command` enum. Lives in its own
//! module so adding a Command variant requires editing only one
//! place per concern (RBAC tags here, dispatch arms in
//! `super::dispatch_command`). Any new variant that isn't added
//! here falls through the match and triggers a compile error —
//! safer than a runtime "unknown" denial.

use foyer_schema::Command;

pub(crate) fn command_tag(cmd: &Command) -> &'static str {
    match cmd {
        Command::Subscribe => "subscribe",
        Command::RequestSnapshot => "request_snapshot",
        Command::ClockProbe { .. } => "clock_probe",
        Command::ProbeSessionRecovery { .. } => "probe_session_recovery",
        Command::AudioBufferReport { .. } => "audio_buffer_report",
        Command::RequestIngressLatency { .. } => "request_ingress_latency",
        Command::SetIngressCaptureLatency { .. } => "set_ingress_capture_latency",
        Command::SetIngressRingPrimeMs { .. } => "set_ingress_ring_prime_ms",
        Command::SetMidiCaptureLatency { .. } => "set_midi_capture_latency",
        Command::SetFakeLatency { .. } => "set_fake_latency",
        Command::SetIngressManualOffsetMs { .. } => "set_ingress_manual_offset_ms",
        Command::StartIngressCalibration { .. } => "start_ingress_calibration",
        Command::StopIngressCalibration { .. } => "stop_ingress_calibration",
        Command::UndoGroupBegin { .. } => "undo_group_begin",
        Command::UndoGroupEnd => "undo_group_end",
        Command::ControlSet { .. } => "control_set",
        Command::AudioEgressStart { .. } => "audio_egress_start",
        Command::AudioEgressStop { .. } => "audio_egress_stop",
        Command::SubscribeSpectrum { .. } => "subscribe_spectrum",
        Command::UnsubscribeSpectrum { .. } => "unsubscribe_spectrum",
        Command::AudioIngressOpen { .. } => "audio_ingress_open",
        Command::AudioIngressClose { .. } => "audio_ingress_close",
        Command::LatencyProbe { .. } => "latency_probe",
        Command::ListActions => "list_actions",
        Command::InvokeAction { .. } => "invoke_action",
        Command::ListRegions { .. } => "list_regions",
        Command::ListAudioPool => "list_audio_pool",
        Command::ImportAudio { .. } => "import_audio",
        Command::ListPlugins => "list_plugins",
        Command::BrowsePath { .. } => "browse_path",
        Command::OpenSession { .. } => "open_session",
        Command::SaveSession { .. } => "save_session",
        Command::RenderSession { .. } => "render_session",
        Command::UpdateRegion { .. } => "update_region",
        Command::DeleteRegion { .. } => "delete_region",
        Command::CreateRegion { .. } => "create_region",
        Command::DuplicateRegion { .. } => "duplicate_region",
        Command::DuplicateRegionRange { .. } => "duplicate_region_range",
        Command::StretchRegion { .. } => "stretch_region",
        Command::SplitRegion { .. } => "split_region",
        Command::ReverseRegion { .. } => "reverse_region",
        Command::CombineRegions { .. } => "combine_regions",
        Command::StripSilenceRegion { .. } => "strip_silence_region",
        Command::PitchShiftRegion { .. } => "pitch_shift_region",
        Command::ListWaveform { .. } => "list_waveform",
        Command::ClearWaveformCache { .. } => "clear_waveform_cache",
        Command::ListBackends => "list_backends",
        Command::LaunchProject { .. } => "launch_project",
        Command::ListSessions => "list_sessions",
        Command::SelectSession { .. } => "select_session",
        Command::CloseSession { .. } => "close_session",
        Command::ShimQuit => "shim_quit",
        Command::ReattachOrphan { .. } => "reattach_orphan",
        Command::DismissOrphan { .. } => "dismiss_orphan",
        Command::ListRecents => "list_recents",
        Command::ForgetRecent { .. } => "forget_recent",
        Command::ClearRecents => "clear_recents",
        Command::CreateTrack { .. } => "create_track",
        Command::UpdateTrack { .. } => "update_track",
        Command::DeleteTrack { .. } => "delete_track",
        Command::ReorderTracks { .. } => "reorder_tracks",
        Command::SetTrackMidiChannelMode { .. } => "set_track_midi_channel_mode",
        Command::CreateGroup { .. } => "create_group",
        Command::UpdateGroup { .. } => "update_group",
        Command::DeleteGroup { .. } => "delete_group",
        Command::AddPlugin { .. } => "add_plugin",
        Command::AddDefaultInstrument { .. } => "add_default_instrument",
        Command::RemovePlugin { .. } => "remove_plugin",
        Command::MovePlugin { .. } => "move_plugin",
        Command::ListPluginPresets { .. } => "list_plugin_presets",
        Command::ListMidiPatchNames { .. } => "list_midi_patch_names",
        Command::LoadPluginPreset { .. } => "load_plugin_preset",
        Command::SavePluginPreset { .. } => "save_plugin_preset",
        Command::OpenPluginGui { .. } => "open_plugin_gui",
        Command::ClosePluginGui { .. } => "close_plugin_gui",
        Command::AddNote { .. } => "add_note",
        Command::UpdateNote { .. } => "update_note",
        Command::DeleteNote { .. } => "delete_note",
        Command::ReplaceRegionNotes { .. } => "replace_region_notes",
        Command::AddPatchChange { .. } => "add_patch_change",
        Command::UpdatePatchChange { .. } => "update_patch_change",
        Command::DeletePatchChange { .. } => "delete_patch_change",
        Command::SetTrackMidiPatch { .. } => "set_track_midi_patch",
        Command::SetSequencerLayout { .. } => "set_sequencer_layout",
        Command::ClearSequencerLayout { .. } => "clear_sequencer_layout",
        Command::MidiInput { .. } => "midi_input",
        Command::SetTrackInput { .. } => "set_track_input",
        Command::ListPorts { .. } => "list_ports",
        Command::AddSend { .. } => "add_send",
        Command::RemoveSend { .. } => "remove_send",
        Command::SetSendLevel { .. } => "set_send_level",
        Command::Undo => "undo",
        Command::Redo => "redo",
        Command::SetAutomationMode { .. } => "set_automation_mode",
        Command::AddAutomationPoint { .. } => "add_automation_point",
        Command::UpdateAutomationPoint { .. } => "update_automation_point",
        Command::DeleteAutomationPoint { .. } => "delete_automation_point",
        Command::ReplaceAutomationLane { .. } => "replace_automation_lane",
        Command::Locate { .. } => "locate",
        Command::SetLoopRange { .. } => "set_loop_range",
        Command::AudioStreamOpen { .. } => "audio_stream_open",
        Command::AudioStreamClose { .. } => "audio_stream_close",
        Command::AudioSdpAnswer { .. } => "audio_sdp_answer",
        Command::AudioIceCandidate { .. } => "audio_ice_candidate",
        Command::TunnelCreateToken { .. } => "tunnel_create_token",
        Command::TunnelRevokeToken { .. } => "tunnel_revoke_token",
        Command::TunnelSetEnabled { .. } => "tunnel_set_enabled",
        Command::TunnelStart { .. } => "tunnel_start",
        Command::TunnelStop => "tunnel_stop",
        Command::TunnelRequestState => "tunnel_request_state",
        Command::ChatSend { .. } => "chat_send",
        Command::ChatClear => "chat_clear",
        Command::ChatHistoryRequest => "chat_history_request",
        Command::ChatSnapshot { .. } => "chat_snapshot",
        Command::PttStart => "ptt_start",
        Command::PttStop => "ptt_stop",
        Command::SetTrackBrowserSource { .. } => "set_track_browser_source",
        Command::ListTrackBrowserSources => "list_track_browser_sources",
        Command::AgentSend { .. } => "agent_send",
        Command::AgentStop => "agent_stop",
        Command::AgentClearHistory => "agent_clear_history",
        Command::AgentSetAutonomy { .. } => "agent_set_autonomy",
        Command::AgentSetConfig { .. } => "agent_set_config",
        Command::AgentConfirmTool { .. } => "agent_confirm_tool",
        Command::AgentHistoryRequest => "agent_history_request",
        Command::AgentListSkills => "agent_list_skills",
        Command::AgentUploadSkill { .. } => "agent_upload_skill",
        Command::AgentEnableSkill { .. } => "agent_enable_skill",
        Command::AgentDisableSkill { .. } => "agent_disable_skill",
        Command::AgentListMemories => "agent_list_memories",
        Command::AgentSaveMemory { .. } => "agent_save_memory",
        Command::AgentForgetMemory { .. } => "agent_forget_memory",
        Command::AgentListTemplates => "agent_list_templates",
        Command::AgentRenderResult { .. } => "agent_render_result",
        Command::AgentSessionList => "agent_session_list",
        Command::AgentSessionNew { .. } => "agent_session_new",
        Command::AgentSessionLoad { .. } => "agent_session_load",
        Command::AgentSessionDelete { .. } => "agent_session_delete",
        Command::AgentSessionRename { .. } => "agent_session_rename",
        Command::ListScripts => "list_scripts",
        Command::SaveScript { .. } => "save_script",
        Command::DeleteScript { .. } => "delete_script",
        Command::EnableScript { .. } => "enable_script",
        Command::RunScript { .. } => "run_script",
        Command::RecoverDisabledScripts => "recover_disabled_scripts",
        Command::UiActionResult { .. } => "ui_action_result",
        Command::TestResetState => "test_reset_state",
        Command::ListAssetPacks => "list_asset_packs",
        Command::FetchAssetPack { .. } => "fetch_asset_pack",
    }
}
