// Foyer page boot.
//
// How UI variants are discovered:
//
//   1. The Foyer server's `/variants.json` endpoint scans its
//      configured `web_root` for folders named `ui-*` that contain
//      a `package.js`, and returns the list.
//   2. This boot script fetches that list and dynamically imports
//      each one. Each package.js's side-effect is a single
//      `registerUiVariant({...})` call on foyer-core's registry.
//   3. foyer-core's bootstrap then picks a variant — URL `?ui=` >
//      localStorage preference > server default > highest heuristic
//      match — and hands control to its `boot()` function.
//
// To install a new variant you DO NOT edit this file. Drop a folder
// at `<web_root>/ui-myvariant/` (e.g.
// `~/.local/share/foyer/web/ui-myvariant/`) containing `package.js`,
// restart the server so it re-scans, and your variant shows up. See
// `HACKING.md` for the package-js contract.
//
// Fallbacks: if the server doesn't implement `/variants.json` (older
// Foyer build, or a custom host serving these files from a static
// CDN) we fall through to loading `/ui-full/package.js` directly,
// which is the shipping UI. That's the same thing a manual lookup
// would discover; keeps us working in degraded-mode.

import { bootFoyerCore } from "foyer-core";

const FALLBACK_VARIANTS = ["/ui-full/package.js"];

async function discoverVariantPackages() {
  try {
    const res = await fetch("/variants.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`status ${res.status}`);
    const payload = await res.json();
    if (Array.isArray(payload?.variants) && payload.variants.length > 0) {
      return payload.variants.map((id) => `/${id}/package.js`);
    }
    if (Array.isArray(payload) && payload.length > 0) {
      return payload.map((id) => `/${id}/package.js`);
    }
    throw new Error("empty variants list");
  } catch (err) {
    console.warn(`[foyer-boot] /variants.json unavailable (${err?.message ?? err}) — using fallback list`);
    return FALLBACK_VARIANTS;
  }
}

const packages = await discoverVariantPackages();
for (const path of packages) {
  try {
    await import(path);
  } catch (err) {
    console.error(`[foyer-boot] variant at ${path} failed to load:`, err);
  }
}

bootFoyerCore();
